use inventorymanagement;
/*select database*/

CREATE TABLE IF NOT EXISTS CATEGORY(
	CATEGORY_ID INT AUTO_INCREMENT PRIMARY KEY,
    CATEGORY_NAME VARCHAR(50) NOT NULL,
    CATEGORY_DESC VARCHAR(100) NOT NULL
);

CREATE TABLE CUSTOMER(
	CUSTOMER_ID INT AUTO_INCREMENT PRIMARY KEY,
    CUSTOMER_NAME VARCHAR(50) NOT NULL,
    EMPLOYEE_SURNAME VARCHAR(50) NOT NULL,
    CUSTOMER_ADDRESS VARCHAR(100) NOT NULL,
    CUSTOMER_CITY VARCHAR(20) NOT NULL,
    CUSTOMER_PHONE CHAR(11) NOT NULL UNIQUE,
    CUSTOMER_EMAIL CHAR(50) NOT NULL
);

CREATE TABLE EMPLOYEE(
	EMPLOYEE_ID INT AUTO_INCREMENT PRIMARY KEY,
    EMPLOYEE_NAME VARCHAR(50) NOT NULL,
    EMPLOYEE_SURNAME VARCHAR(50) NOT NULL,
    EMPLOYEE_ADDRESS VARCHAR(100) NOT NULL,
    EMPLOYEE_PHONE CHAR(11) NOT NULL UNIQUE,
    EMPLOYEE_EMAIL CHAR(50) NOT NULL,
	ROLES_ID INT
    
	
		
);

CREATE TABLE IF NOT EXISTS ROLES(
	ROLES_ID INT AUTO_INCREMENT PRIMARY KEY,
    ROLES_TITLE VARCHAR(50) NOT NULL,
    ROLES_DESC VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS ORDERS(
	ORDERS_ID INT AUTO_INCREMENT PRIMARY KEY,
    ORDERS_DATE date NOT NULL,
    ORDERS_ADDRESS VARCHAR(100) NOT NULL,
    EMPLOOYE_ID INT, 
	CUSTOMER_ID INT,
    SHIP_ID INT
		      
);

CREATE TABLE IF NOT EXISTS ORDERSDETAILS(
	ODS_ID INT AUTO_INCREMENT PRIMARY KEY,
    ORDERS_ID INT,
    PRODUCT_ID INT,
    UNITPRICE SMALLINT NOT NULL, 
	QUANTITY INT NOT NULL,
    DISCOUNT DECIMAL NOT NULL
        
		      
);

CREATE TABLE IF NOT EXISTS PRODUCT(
	PRODUCT_ID INT AUTO_INCREMENT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(50) NOT NULL,
    SUPPLIER_ID INT,
    CATEGORY_ID INT, 
	UNIT_PRICE INT NOT NULL,
    STOCK_QUANTITY INT NOT NULL,
    QUANTITY_TYPE_PER_UNIT VARCHAR(100) NOT NULL
        
		      
);

CREATE TABLE IF NOT EXISTS SHIP(
	SHIP_ID INT AUTO_INCREMENT PRIMARY KEY,
    SHIP_COMPANY_NAME VARCHAR(100) NOT NULL,
    SHIP_COMPANY_PHONE CHAR(11) UNIQUE
);

CREATE TABLE IF NOT EXISTS SUPPLIER(
	SUPPLIER_ID INT AUTO_INCREMENT PRIMARY KEY,
    SUPPLIER_COMPANY_NAME VARCHAR(50) NOT NULL,
    CONTACT_ID INT
);

CREATE TABLE IF NOT EXISTS CONTACT(
	CONTACT_ID INT AUTO_INCREMENT PRIMARY KEY,
    CONTACT_NAME VARCHAR(50) NOT NULL,
    CONTACTTITLE_ID INT,
    CONTACT_ADDRESS VARCHAR(100) NOT NULL,
    CONTACT_CITY VARCHAR(50) NOT NULL,
    CONTACT_PHONE CHAR(11) NOT NULL UNIQUE,
    CONTACT_EMAIL VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS CONTACTTITLE(
	CONTACTTITLE_ID INT AUTO_INCREMENT PRIMARY KEY,
    CONTACTTITLE_TYPE VARCHAR(50)
);

CREATE TABLE IF NOT EXISTS WAREHOUSE(
	WAREHOUSE_ID INT AUTO_INCREMENT PRIMARY KEY,
    WAREHOUSE_NAME VARCHAR(50) NOT NULL,
    WAREHOUSE_TYPE VARCHAR(50) NOT NULL,
    WAREHOUSE_LOCATION VARCHAR(100) NOT NULL,
    CATEGORY_ID INT,
    PRODUCT_ID INT
);

